version: '3.4'

services:
  sensocomum.apis.commands:
    image: ${DOCKER_REGISTRY}sensocomumapiscommands
    build:
      context: .
      dockerfile: SensoComum.APIs.Commands/Dockerfile

  sensocomum.apis.queries:
    image: ${DOCKER_REGISTRY}sensocomumapisqueries
    build:
      context: .
      dockerfile: ../SensoComum.APIs.Queries/Dockerfile

