version: '3.4'

services:
  sensocomum.apis.commands:
    image: ${DOCKER_REGISTRY}sc.apis.commands
    build:
      context: ./SensoComum.APIs.Commands
      dockerfile: Dockerfile

  sensocomum.apis.queries:
    image: ${DOCKER_REGISTRY}sc.apis.queries
    build:
      context: ./SensoComum.APIs.Queries
      dockerfile: Dockerfile

